### ISSUE TITLE
NtWriteVirtualMemory return STATUS_ACCESS_VIOLATION

### ISSUE THREAD

**Issue by zero-ms** [crummie5/FreshyCalls#8]
```
NTSTATUS Status;

LPVOID BasePointer = NULL;
SIZE_T BaseSize = 1024;

char Payload[2048];
memset(Payload, 0, 2048);

Status = syscall.CallSyscall("NtAllocateVirtualMemory", NtCurrentProcess,
                            &BasePointer, 0, &BaseSize,
                            MEM_COMMIT | MEM_RESERVE, PAGE_EXECUTE_READWRITE)
                            .result;

Status = syscall.CallSyscall("NtWriteVirtualMemory", NtCurrentProcess,
                            BasePointer, Payload, 1024, nullptr)
                            .result;
```

NtWriteVirtualMemory return code is STATUS_ACCESS_VIOLATION(0xC0000005)
I'm still a beginner, so I don't know why the error occurs and how to debug it...

OS: Windows 11
Arch: x64
Compiler: Visual Studio 2022

**Comment by zero-ms** [comment]
Sometimes there is a STATUS_PARTIAL_COPY(0x8000000D) error.

**Comment by ElephantSe4l** [comment]
Probably related to #2 
FreshyCalls use C++ templates with variadic parameters so it only knows the type of what you use as parameter. For example, `NtAllocateVirtualMemory`, the third argument is a pointer. You are passing 0 as value which by default is going to be 4 bytes but a pointer will be 8 bytes (on x64). You have 4 bytes that are going to be uninitialized  which is going to make `NtAllocateVirtualMemory` interpret it as another value. Just cast all the types to the correct ones.
